updating puppet installation

diff --git a/templates/scripts/firstboot.erb b/templates/scripts/firstboot.erb
--- a/templates/scripts/firstboot.erb
+++ b/templates/scripts/firstboot.erb
@@ -22,15 +22,23 @@ else
 fi
 
 
-echo '### INSTALLING PUPPETLABS APT REPO ###'
-wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb; dpkg -i puppetlabs-release-precise.deb
 
+# this is a debian/ubuntu specific command
+release=`lsb_release -c | awk '{print $2}'`
+
+echo '### INSTALLING PUPPETLABS APT REPO ###'
+wget http://apt.puppetlabs.com/puppetlabs-release-$release.deb; dpkg -i puppetlabs-release-$release.deb
+if [ $? $test -eq 1 ]; then
+   echo "Could not find puppetlabs release for $release.  Trying alternative."
+   wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb; dpkg -i puppetlabs-release-precise.deb
+fi
 
 echo '### UPDATING AND INSTALLING NECESSARY PACKAGES ###'
-apt-get update -y && apt-get install -y openssh-server git puppet ruby1.9.1 ruby1.9.1-dev rubygems
+apt-get update -y && apt-get install -y openssh-server git puppet ruby ruby-dev
+
 
 echo "### INSTALLING  LIBRARIAN-PUPPET-MAESTRODEV DUE TO BUGFIXES IN LIBRARIAN-PUPPET ###"
-gem install librarian-puppet-maestrodev
+gem install r10k
 
 
 # Set hostname of puppetmaster
