correcting requirements in metadata.json and Puppetfile

diff --git a/templates/scripts/postinstall.erb b/templates/scripts/postinstall.erb
--- a/templates/scripts/postinstall.erb
+++ b/templates/scripts/postinstall.erb
@@ -1,7 +1,15 @@
 #!/bin/sh
 
+# this is a debian/ubuntu specific command
+release=`lsb_release -c | awk '{print $2}'`
+
 # Install PuppetLabs Apt Repo
-wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb; dpkg -i puppetlabs-release-precise.deb
+echo '### INSTALLING PUPPETLABS APT REPO ###'
+wget http://apt.puppetlabs.com/puppetlabs-release-$release.deb; dpkg -i puppetlabs-release-$release.deb
+if [ $? $test -eq 1 ]; then
+   echo "Could not find puppetlabs release for $release.  Trying alternative."
+   wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb; dpkg -i puppetlabs-release-precise.deb
+fi
 
 # Install Fisrtboot script
 wget http://<%= @ipaddress %>/bin/firstboot -O /root/firstboot
